# Generated by Django 4.2.4 on 2023-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrap_url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
